### ISSUE TITLE
Im getting an error: API Settings Not Set

### ISSUE THREAD

**Issue by jeslabbert** [pascalboucher/laravel-chatkit-api#5]
Hi there,
I am getting this error, yet I have published the vendor file, filled in my environment variables with the correct key and locator. I have tried bypassing the env variables and filling them directly into the config file as well. What else am I missing with this as I have followed the documentation exactly.

Kind Regards

**Comment by pascalboucher** [comment]
Hi @jeslabbert 

It seems like you forgot to authenticate with the api. You need to authenticate **before** you make an api call. Behind the seen, this package uses [the official sdk's authentication method](https://docs.pusher.com/chatkit/reference/server-php#authenticate-a-user) which ask for a user id to authenticate with chatkit's servers.

So yeah just add this :  

`
Chatkit::withUser($userId);
`

Before your api call

You can head over to the example in the usage section of the documentation for a more complete code example.

[Documentation](https://github.com/pascalboucher/laravel-chatkit-api/wiki#usage)

Please provide a code snippet if this doesn't work for you and I'll be happy to help.
