### ISSUE TITLE
'Api settings not set'

### ISSUE THREAD

**Issue by evinkuraga** [pascalboucher/laravel-chatkit-api#6]
First off, thanks for this amazing package and incredible documentation. Really, hats off to how through your documentation is!

I've just installed it today. I'm running into an issue when trying to create a user. I'm using your default example:

```
$user = Chatkit::users()->store([
    'id' => 123,
    'name' => 'John Doe',
    'avatar_url' => 'https://placekitten.com/200/300'
]);
```

Running this ends up giving me the following:
`'Api settings not set'`

This fails at this point in:
 ```
protected function getHttpClient(): Client
    {
        if (is_null($this->httpClient)) {
 
            if (!array_key_exists('userId', $this->api) || !array_key_exists('sudo', $this->api)) {
                throw new \Exception('Api settings not set');
            }
 
            ....
        }
 
        return $this->httpClient;
    }

```
I've dd the $this->api. It's an empty array. 

Thanks for looking into this!

**Comment by pascalboucher** [comment]
Hi @evinkuraga !

You can head over to this [issue](https://github.com/pascalboucher/laravel-chatkit-api/issues/5) which had a similar situation has you.

Basically you can find an example on how to use the package in the [usage section](https://github.com/pascalboucher/laravel-chatkit-api/wiki#usage) of the documentation (there is an example)

If you still have a problem after that, I'll be glad to help! :)

**Comment by evinkuraga** [comment]
Hi @pascalboucher , thank you very much for this answer. This has indeed resolved the issue. If I may propose, I think it would be a good clarification to add to the main document. 

**For all those who fall on this issue page, here is a little more clarification to help you through this issue:**
In order to use any methods listed in the documentation, you will first need to create a first user which can be created through the chatkit dashboard. Make sure to give this user the admin role. Although you have a method to create users, you must first authenticate your app which requires chatkit to have at least 1 user listed. Contrary to what I thought, your apikey and instancelocator are not sufficient, which led me to ask this question.

Here's a step by step guide to guide to get you up and running with this great package:
0. Create an account on pusher chatkit.
1. Follow the instructions listed in the documentation first page (composer require, publish package, etc.)
2a. Create a user in the chatkit dashboard (found under the instance inspector section). 
2b. Make sure to give this user admin role and give him all permissions.
3. When ever you user a method, you will have to use this following line first:
```
Chatkit::withUser("YOUR_APP_USERID/NAME");
// OR (depending on whether the method says "sudo" in the title
Chatkit::withSudoUser("YOUR_APP_USERID/NAME");

//Follow this with the method you plan on using:
$user = Chatkit::users()->store([
    'id' => $userId,
    'name' => 'John Doe',
    'avatar_url' => 'https://placekitten.com/200/300',
    'custom_data' => [
        'my_custom_key' => 'some data'
    ]
]);
```

**Comment by pascalboucher** [comment]
Thanks !

I just want to add to @evinkuraga 's comment that on some api calls, you will need to authenticate with the actual chatkit id of the resource you are trying to access.

For example if you want a user to [join a room](https://github.com/pascalboucher/laravel-chatkit-api/wiki/Users#join-a-room)

```
// User ID in request must match User ID in access token

Chatkit::withUser($userId);

$user = new \Chess\Chatkit\Models\User($userId);

$room = $user->room($roomId)->join();

```
